### PR TITLE
Wrapping items in Ember.Array to provide uniform access to data

### PR DESCRIPTION
**Pull request by pete-the-pete**
I was seeing the same problem reported in #55.  In my case, I am passing in the results from my model hook.  This results in an error when trying to access a property in the component used in the ember collection.

For example, using this:
```
  {{#ember-collection
    items=results
    height=500
    width=800
    cell-layout=(fixed-grid-layout 800 50) as |item index|
  }}
    {{my-component foo=item}}
  {{/ember-collection}}
```

I would get an error when trying to access data from the passed in item:
```
this.getAttr('foo').get('bar') --> throws something like  'get is not a function of `undefined`'
```

The problem is that updateItems gets 'undefined' when accessing item[itemIndex].  The result list has the correct length, but no data.

### CODE REVIEW

**Comment by stefanpenner** [comment]
:+1:

**Comment by krisselden** [comment]
tests are broken

**Comment by pete-the-pete** [comment]
@krisselden I saw this just running the tests from master, I opened another issue #61.

I would help look into it, but I don't really know where/how to dive in.

**Comment by lukemelia** [comment]
@pete-the-pete if you rebase on master, I've resolved #61

**Comment by lukemelia** [comment]
Closing in favor of #66

**Pull request closed without merging**
