### PR TITLE
Fix /simple in dummy app

### PR DESCRIPTION
**Pull request by jonnii**
This makes the model return an `Ember.Array` and only
conditionally sets styles.

### CODE REVIEW

**Comment by jonnii** [comment]
@stefanpenner @mmun i think this is ready to go.

**Comment by mmun** [comment]
I don't have a good working knowledge of the code yet. Can you explain why the guard is justified? Also, please squash.

**Comment by jonnii** [comment]
@mmun `this.contentElement` is undefined until `didInsertElement` runs, but the bounds are being calculated as soon as attrs are set, which seems weird to me. What's happening is that it's attempting to set the width and height before the element is in the dom.

**Comment by raytiley** [comment]
I'm seeing this with master right now as well. Not sure when this happened... my last time working with this code the dummy app was working, now its broken.

**Comment by jonnii** [comment]
@raytiley i think it's a missing call to _super in one of the lifecycle hooks. maybe. maybe not.

**Pull request closed without merging**
