### PR TITLE
Move fixed styles into css and cleanup

### PR DESCRIPTION
**Pull request by BryanCrotaz**

### CODE REVIEW

**Comment by mmun** [comment]
First two commits look good.

@krisselden what do you think about b9959eff9bb22f9721aee88570e468fc1d115143?

**Comment by BryanCrotaz** [comment]
Without the latter, users cannot override the style. In my case I want to change the overflow in a table with fixed width.

**Comment by jonnii** [comment]
I thought we were trying to get away from having class names on this component.

**Comment by BryanCrotaz** [comment]
Is there a way to apply CSS without a class name?
And what's wrong with having a class name? It's unlikely to cause bloat as you wouldn't have many on a page.

**Comment by BryanCrotaz** [comment]
Style on the element takes precedence over everything else so should be reserved for truly dynamic styling like width for example

**Comment by mmun** [comment]
@BryanCrotaz I agree it should be overridable. I want to Kris to sign-off on it though.

**Comment by mmun** [comment]
@jonnii Mostly we wanted to get rid of the ember-collection-list-item class. A top level class is fine. Ideally we'd use a custom element, `<ember-collection>`, but the web isn't ready for that yet.

**Comment by BryanCrotaz** [comment]
That would be better...

**Comment by raytiley** [comment]
So one thing @krisselden and I talked about during our initial spike was the ability to use different strategies for the positioning. Ideally the consumer of `ember-collection` could pass in some object to delegate the style needed for different strategies. The one downside of this approach is that you now have two different locations to change the strategy for positioning. You would need to override the style in your app, as well as providing the delegate which can generate a style for each item.

One thing I did notice, is we probably want to add the `addon.css` in the `included` hook so that the styles are imported by default if we go down this path. Without these styles applied the component won't work at all.

**Comment by BryanCrotaz** [comment]
An attached object could still inject element style and override the default css. But you can't do it the other way around.

**Comment by jonnii** [comment]
Why not have a default set of styles and if someone wants to override then they can extend the component>

**Comment by BryanCrotaz** [comment]
> Why not have a default set of styles and if someone wants to override then they can extend the component?

Because an application developer shouldn't have to extend all their components in order to apply a consistent css style across all of them. Think about how many visual components a typical application needs - we should be able to drop them in and pass it to a graphic artist for styling.

**Comment by lukemelia** [comment]
@BryanCrotaz would you mind splitting this into 2 PRs? One with the first two commits, which can be merged right away, and the other with the css change, which needs a little more discussion.

**Comment by lukemelia** [comment]
The changes in the first two commits have been covered or obviated, and we'll hold off on moving stuff to external css for now.

**Pull request closed without merging**
