### PR TITLE
Use Xunit reporter in CI. 

### PR DESCRIPTION
**Pull request by rwjblue**
This will allow circle to show us much better UI (showing us test names and such).

Still working on some changes to ember-cli and ember-try to make this work well.

### CODE REVIEW

**Comment by rwjblue** [comment]
OK, with these changes CircleCI now can detect individual test pass/fail information.  Some screenshots from [this build](https://circleci.com/gh/emberjs/ember-collection/204):

test summary

artifacts

sample artifact contents

**Comment by raytiley** [comment]
:+1:  SWEET

I'm going to start migrating all he commented out tests next week. Seeing the breakdowns will be nice.

**Comment by rwjblue** [comment]
ember-cli@2.3.0-beta.2 has been released (and I updated to unlock from the SHA here)

**Comment by rwjblue** [comment]
Updated to ember-try@0.1.2 (removing SHA lock).  This is ready to go now...

**Pull request merged**
