### PR TITLE
rename to ember-collection

### PR DESCRIPTION
**Pull request by jonnii**
This PR attempts to rename the component from `ember-list-view` to `ember-collection`. There are certainly things I've missed, but hopefully this is a good start.

I believe this is the first step that's required to get this published as an addon under the name `ember-collections`.

### CODE REVIEW

**Comment by stefanpenner** [comment]
awesome thanks :)

**Comment by jonnii** [comment]
@stefanpenner will emberaddons pick this up automatically?

**Comment by stefanpenner** [comment]
after a release

**Comment by jonnii** [comment]
@stefanpenner good to know, I may take a stab and getting some more tests passing.

**Comment by stefanpenner** [comment]
:)

**Pull request merged**
