### PR TITLE
Rename ember-list-container to ember-collection-container

### PR DESCRIPTION
**Pull request by jonnii**

### CODE REVIEW

**Comment by jonnii** [comment]
I'll tackle the list-view-item classes after this one.

**Comment by jonnii** [comment]
@mmun should be ready to go

**Comment by mmun** [comment]
@jonnii Actually we want to remove the classes entirely and instead have the users put them in if they want. E.g. we should add a container class to `https://github.com/emberjs/ember-collection/blob/master/tests/templates/fixed-grid.js` and rewrite tests to use that. Same deal for the `list-item` class thats already there.

**Comment by jonnii** [comment]
So that would mean getting rid of the `<div class="ember-collection-container">` in the `template.hbs` for the component?

**Comment by mmun** [comment]
@jonnii Yes, specifically...
- Remove the `ember-list` class in the component's javascript file.
- Remove the `ember-list-container` and `ember-list-item-view` classes in the component's template.

**Comment by jonnii** [comment]
I suppose that leaves everything to the user. I'm with you now.

**Comment by mmun** [comment]
Sorry I didn't communicate this sooner. I'm try to balance a bunch of things :sob:

**Comment by jonnii** [comment]
no prob!

**Comment by mmun** [comment]
Oops you deleted it too quickly :D. This was my plan:

1. Merge this PR.
2. Also merge the one for list-items.
3. Leave tests the way they are but change https://github.com/emberjs/ember-collection/blob/master/tests/templates/fixed-grid.js to include them by default.

**Comment by mmun** [comment]
so basically

```
hbs`{{#ember-collection
    items=content
    cell-layout=(fixed-grid-layout itemWidth itemHeight)
    width=width
    height=height 
    offset-x=offsetX
    offset-y=offsetY
    class="ember-collection-container"
    as |item| ~}}
  <div class="ember-collection-list-item">{{item.name}}</div>
{{~/ember-collection~}}`;
```

**Comment by mmun** [comment]
Do you mind pushing again?

**Comment by jonnii** [comment]
@mmun will make other PRs for this.

**Comment by mmun** [comment]
Sweet. thanks.

**Pull request closed without merging**
