### PR TITLE
Hook up CircleCI

### PR DESCRIPTION
**Pull request by mmun**

### CODE REVIEW

**Comment by stefanpenner** [comment]
why drop travis?

**Comment by mmun** [comment]
To test in Firefox and Chrome.

**Comment by stefanpenner** [comment]
this also does not appear to be using ember try

**Comment by mmun** [comment]
It is.

**Comment by stefanpenner** [comment]
ah the run is, but in serial. Can circle when them concurrently?

**Comment by mmun** [comment]
Not sure - mostly I just wanted to get it running ASAP. I am happy to switch back to travis (We probably we to use Sauce labs anyways to test multiple browsers)

**Comment by mmun** [comment]
Thanks for the suggestion @stefanpenner. I hooked up 4x concurrent builds, one for each ember try scenario.

**Comment by stefanpenner** [comment]
Nice

**Pull request merged**
