### PR TITLE
Format style can now take a string value for width. Eg. '100%'

### PR DESCRIPTION
**Pull request by mrinterweb**
I added this because I wanted to pass width="100%" to the component. This commit optionally lets the list view occupy a non pixel width.

### CODE REVIEW

**Comment by lukemelia** [comment]
This would need to be accompanied by tests. @krisselden has been thinking about layouts supporting percentages and may have additional thoughts.

**Comment by mrinterweb** [comment]
It looks like the old tests/acceptance/list-view-test.js is mostly commented out. Not sure where a test like this should go at this time.

**Comment by billdami** [comment]
+1 for this, since the component is already monitoring and re-rendering the list when the container size changes, it feels intuitive to have to specify a static pixel width for the list items for a simple (non grid-like) list. If you have a list whose items span the entire width of the container, you need to monitor the window/container size changes yourself, so that the width of the items are adjusted as needed.

Would be nice to just be able to do something like:
```
{{#ember-collection items=model  cell-layout=(fixed-grid-layout 'auto' 50) as |item index|}}
```

**Comment by nkgm** [comment]
+11111 this is the very basis for infinite tables and working beautifully for me so far. I can see how this might not fully belong in `fixed-grid-layout`, since using 50% or 30% wouldn't pack them properly as you'd expect from a "grid-layout", but why not have a dedicated `full-width-layout` where you only specify pixel height and you're good to go.

**Comment by raytiley** [comment]
@mrinterweb does this PR solve your problem? https://github.com/emberjs/ember-collection/pull/81

You can now override a layout and provide your own function for generating the style. This allows you to create layouts that can use percentages.

See https://github.com/emberjs/ember-collection/blob/master/addon/layouts/percentage-columns.js for an example.

**Comment by mrinterweb** [comment]
@raytiley if your PR allows for layouts that accept percentage based column widths, then yes. I know that this PR works for me, and I've been using my forked branch so I could have this feature. Not sure when I'll have the time, but I'll try out the main ember-collection repo now that columns can be given a percentage.

**Pull request closed without merging**
