### PR TITLE
Fixes offset bug; adds actions; fixes (more) tests

### PR DESCRIPTION
**Pull request by shaunc**
The offset bug is fixed now; I've changed the layout-bin-packer dependency temporarily pending action from @stefanpenner.

The old tests checked startingIndex computed property (which is the first visible item). It seemed to me the corresponding 2.0 interface would be to allow an action to observe this -- so have added `startingIndexDidChange` and `visibleCountDidChange` (number of items visible). 

I had difficulty testing these. You can't just use `<integration-test-context>.set('action-name', function())` ... I tried various things and in the end wrote a wrapper object in the dummy application, which I think is quite awkward. If there is a better way to test, please let me know! :)

All the tests for "fixedGrid" are now working. I still need to write tests for "mixedGrid".

### CODE REVIEW

**Comment by stefanpenner** [comment]
you now have commit (and shortly when i know your NPM username npm push) to layout-bin-packer

**Comment by shaunc** [comment]
cleaned up layout-bin-packer -- will commit & bump patch version in morning. Then I think this will be ready to go with that (doesn't pass now because of layout-bin-packer).

**Comment by shaunc** [comment]
Hmm... I have more things to add, but am eager to get this PR in first. It seems that ember non-canary tests are failing. Perhaps someone with some insight into what the differences are between canary and previous could take a look? I'll be on the road for several days, and don't know if I'll have time to go back and debug previous ember. (PS -- what does the "beta" branch refer to? Perhaps circleci should reference 2.0 now that its out?)

**Comment by mmun** [comment]
Ember canary is failing too (4 failing tests). It just shows a green checkmark because we allow canary to fail.

**Comment by jonnii** [comment]
Ideally ember-collection would work with 1.13 as without that list-view users have no real recourse for upgrading to 2.0.

**Comment by stefanpenner** [comment]
@jonnii if it works in 2.0.0, it works in 1.13

**Comment by jonnii** [comment]
@stefanpenner that would be my expectation too.

**Comment by stefanpenner** [comment]
we should be sure CI reflects that

**Comment by shaunc** [comment]
... hmm... cleaned up / reinstalled from npm & bower, but couldn't reproduce these failures on canary....

**Comment by stefanpenner** [comment]
i think GH is having issues.

**Comment by shaunc** [comment]
That may be -- the actual failure "scrollTop" -- everything in the test is divisible by 50, but the actual value is 80. But I was also wondering if it could be a timing issue... that the scrollTop attribute hasn't had time to get to final value. (though 80 would still be too big -- but I would be less sceptical if the "wrong answer" was 100).

Ah well -- github has everyone else's issues; perhaps it thinks it deserves some of its own. :) 

It would be great if someone else could pull my branch and tell me if it was failing.

**Comment by mmun** [comment]
@shaunc I'm not comfortable merging this until we resolve our existing tech debt (_maybeMutAttrs and lack of array observation). Is there anything in this commit that should be cherry-picked in the meantime? Can the `layout-bin-packer` stuff be merged separately?

**Comment by raytiley** [comment]
I've been a bit quiet lately, but I have some time scheduled tomorrow day and during the portland Maine ember unconference to work on ember-collection. I can work on some of this tech debt tomorrow.

**Comment by shaunc** [comment]
@mmun -- that stuff you mention is bad and should definitely be resolved... however, all of that was in the last pull you accepted from me :). This is pretty much all new tests & fixes of bugs that they revealed (the layout-bin-packer stuff being the most technical but there were several other small things as well); it does include one feature -- adding actions for startingIndex & visibleCount observers.

I would be inclined to think it should go in ... or possibly you should undo the last pull if you don't like that stuff. Without it we have very little test coverage and shouldn't really move forward at all until that is fixed.

I'd also like to get the mixed-grid layout tests in, but don't want to add to the logjam.

As I said in previous pull request -- the _maybeMutAttrs is a hack to get around https://github.com/emberjs/ember.js/issues/11992 -- the call to didReceiveAttrs at the end of init is there for the same reason.

I could try to get array observation working. I tried it and it failed the tests I had working, but presumably I was just in a rush and did something wrong. But ... nevertheless... ceteris paribus more tests are good.

**Comment by rwjblue** [comment]
I believe that 11192 is fixed in 1.13.8.

**Comment by shaunc** [comment]
@rwjblue -- great... I have something else to check in tonight (NB still in European time), but after I'm done I'll try backing the _maybeMutAttrs out and testing in 13.8. ...umm... but doesn't that mean that it should be fixed in canary? Or do you mean it hadn't yet been introduced in 13.8?

**Comment by shaunc** [comment]
@mmun -- takes care of _maybeMutAttrs & array observer, as well as fix of test for safari and some async issues which could have been causing circleci failures.

**Comment by shaunc** [comment]
@mmun -- I feel its a bit absurd that I'm maintaining the tests on a separate branch while you are checking in things that break them. If you don't want to check them in, perhaps you could at least try running them before you check in other things? This is perhaps the third time I've had to (re)fix bugs, and I don't have time right now... The code does look much better, but its not passing the tests again. I may have some time tomorrow... if you don't want to incorporate these tests, though, I suggest you write some of your own before you change the code-base.

**Comment by mmun** [comment]
@shaunc The reality is that this PR is too difficult for any of the maintainers to review. Our goal is not to ship this as quickly as possible, but to write something that is maintainable. Keep in mind that we have to maintain it for years. We need to break this PR up into smaller chunks (whether you do it, or someone else does).

**Comment by mmun** [comment]
I'm working on cherry-picking b0afc3a5d00da2ecc63279d1a495d59868c21339.

**Comment by mmun** [comment]
So the remaining interesting looking commits are

- fixed grid tests passing: e959201f04113a3a538d85dcd322bd794e41e996
  - This introduces `startingIndexDidChange`/`visibleCountDidChange` which we did not discuss. We don't want this to be a public API for the first release. The tests should be rewritten not to depend on startingIndex/visibleCount and just inspect the DOM instead.

- protect more against receivedAttrs bug; cleanup of package.json: 34d740daecb1e81674e09fe7563d603e18217c22
  - Where is the test that `(this.attrs != null)` guards against?
  - package.json changes should go in a separate PR.
  - We should not have a (css) class on the component.

- fixes timing issues on scroll; fixes limit of scroll...: 5d2a9107b70e85e5fcb17ba11cdfb1b67e05fcbf
  - @shaunc: this seems like it can be PR'd separately with a short description of the issue for everyone's edification.
  - @krisselden / @raytiley should review this

**Comment by shaunc** [comment]
> Our goal is not to ship this as quickly as possible, but to write something that is maintainable.

The most important part of this PR are tests. I see you've got most of them in now, but in the mean time you checked in a number of non-passing PRs, which is not optimal from the point of view of maintainability IMHO. I do wish that, if you didn't take the code, you would have at least taken the tests (of features you wanted to release) from the beginning. But ... ah well.

> This introduces startingIndexDidChange/visibleCountDidChange

Was in response to old test of computed property (via access to childViews in test). I thought the "DDAA" way would be to allow registration of listener (I have since changed to "sliceDidChange"). In fact I do need some notification method in my own application, but it doesn't have to be this way, and I will exclude it for the moment.

> protect more against receivedAttrs bug; cleanup of package.json: 34d740d

this.attrs != null stuff I think is fixed with call to super in `_didReceiveAttrs`.

> fixes timing issues on scroll; fixes limit of scroll...: 5d2a910

The problem is that if you set scrollTop to an impossible value and then resize to make it possible or closer to possible, browsers react in different ways. I'll see if I can't get it working again in current head :/

**Comment by mmun** [comment]
@shaunc Can you make an issue about sliceDidChange? You're right that conceptually it fits DDAU just fine. We were looking for use cases.

Please know that I feel bad this didn't go smoothly. I tried to make up for it with the cherry-pick of the first commit. Thank you for your hard work.

**Comment by shaunc** [comment]
@mmun -- thanks! I was most annoyed before I realized you'd actually picked up most of the tests.

I was just planning on creating a pull request for sliceDidChange. The use case is in any situation where you need "dual buffering" -- e.g. if you have infinite scroll and you want to issue an ajax request when you get near the edge. I'll create an issue.

First though I'm working on getting you a PR for buffering bug. Right now if buffers only on previous items, not on next items. The fix is quite simple `buffer` -> `buffer * 2` in `count` calculation. However I thought the tests should check in general whether the right elements have rendered (including those in the buffer). Ironically, this is a situation where `sliceDidChange` could come in useful.

BTW -- is there a good way to pass an action handler to a component in a test? You might have noticed the rigamarole with the wrapper I put in to test `sliceDidChange`. Ideally in a test, one could simply do:

    this.set( 'property-bound-to-action-handler', newHandler );

But that doesn't work currently.....

**Comment by mmun** [comment]
> if you have infinite scroll and you want to issue an ajax request when you get near the edge. I'll create an issue.

My use case is that I want to defer an AJAX request until the cell has settled. Similar but not quite the same.

> But that doesn't work currently.....

Hmmmm that seems bad. It should work.

**Comment by mmun** [comment]
@rwjblue says it works, see:

https://github.com/aptible/dashboard.aptible.com/blob/c23db935fe4c361d093505736b8dac99b76f27ed/tests/integration/components/primitive-select-test.js#L43-L59

**Comment by shaunc** [comment]
That test has a bound handler quoted in template  ... hmm -- I didn't try that. That is sufficient -- great! But it should also be possible to somehow pass an unbound handler:

    this.render(hbs('{{primitive-select update=(action "checkValue") items=listing}}'));
    var newValue;
    this.set('update', function(value) { newValue = value; });

    let select = this.$('select');
    Ember.run(function() {
      select.val('two');
      select.trigger('change');
      assert.equal(newValue, "two");
    });

**Comment by mmun** [comment]
`this.set` is setting properties on the context that the component is embedded in, not the component itself. This should work...

```js
this.set('foo', function() { ... });
this.render(hbs`{{foo-bar update=(action foo)}}`);
```

**Comment by shaunc** [comment]
Ah ... :) thanks!

**Comment by shaunc** [comment]
@mmun ... fyi ... 

    this.set('foo', function() { ... });
    this.render(hbs`{{foo-bar update=(action foo)}}`);

Doesn't quite work, but:

    this.set('actions', {});
    this.set('actions.sliceDidChange', function (index, count){
      startingIndex = index;
      visibleCount = count;
    });

does ... :) .. or you can register with `this.on` as in the test example.

**Comment by rwjblue** [comment]
The first example should work. I'd love it if you could submit a failing test to ember-test-helpers (similar and in the same location as [this one](https://github.com/switchfly/ember-test-helpers/blob/master/tests/test-module-for-component-test.js#L241-L245)) for this....

**Comment by shaunc** [comment]
Ok ... do you want me to guard it with the same cruft?

  if (!/^1\.(11|12)/.test(Ember.VERSION)) {

**Comment by jonnii** [comment]
we are only targetting > 1.13 for this, so maybe not necessary?

**Comment by rwjblue** [comment]
> Ok ... do you want me to guard it with the same cruft?

The tests in ember-test-helpers are run against 1.11, 1.12, 1.13, 2.0, 2.1-beta, canary so we do need to guard for that. Can you put the new test in the same `if` block with the one I linked above?

**Comment by shaunc** [comment]
sure

**Comment by shaunc** [comment]
grumble... the test doesnt fail!

    test('calls action handler set in context', function(){
      expect(1);
      this.set('colorChange', function(arg) { 
        equal(arg, 'foo'); });
      this.render(hbs("{{changing-color change=(action colorChange)}}"));
    });

I went back and made sure that the test in ember-collection doesn't work.

If I write:

    this.set('actions', {});
    this.set('actions.sliceDidChange', function (index, count){ ...

The test works. If I change 2nd to:

    this.set('sliceDidChange', function (index, count){ ...

It fails. I tried reinstall npm/bower in case this was a recent fix -- but it could be version of something in package.json in ember collection? Alternately, does the context already have a "colorChange" action?

The error I get when I don't put the action in actions is:

        actual: >
            null
        message: >
            Died on test #1     at Object.test (http://localhost:7357/assets/test-support.js:1826:11)
                at http://localhost:7357/assets/dummy.js:4292:15
                at mod.state (http://localhost:7357/assets/vendor.js:150:29)
                at tryFinally (http://localhost:7357/assets/vendor.js:30:14)
                at requireModule (http://localhost:7357/assets/vendor.js:148:5)
                at Object.TestLoader.require (http://localhost:7357/assets/test-loader.js:29:9)
                at Object.TestLoader.loadModules (http://localhost:7357/assets/test-loader.js:21:18): An action named 'sliceDidChange' was not found in [object Object].

**Comment by mixonic** [comment]
@shaunc I haven't looked at the code here closely, but I wanted to make sure you know `(action "sliceDidChange")` and `(action slideDidChange)` do very different things. It looks like they are just confused in your failures, at a glance.

`(action "sliceDidChange")` will pluck the property `actions.slideDidChange` from the current context, presume it is a function, and wrap it in a closure so it has the correct scope. It will never reference `sliceDidChange` on the context.

`(action slideDidChange)` looks to the context for a `slideDidChange` property (like with `this.set('sliceDidChange', () => {})`), creates a closure without changing the binding and passes the closure down. This usage should never access `actions.slideDidChange` or anything on actions.

**Comment by shaunc** [comment]
@mixonic -- great catch! You are absolutely right! I did know that but my code in the test didn't reflect it, and I overlooked it. My apologies for keeping everyone on edge. :(

**Pull request closed without merging**
