### PR TITLE
Remove arrayObserver when the component is destroyed

### PR DESCRIPTION
**Pull request by pieter-v**
The arrayObserver leaks the component if not removed

### CODE REVIEW

**Comment by rwjblue** [comment]
Seems good to me, but I'm somewhat hesitant to land with CI failing.  The last master build was passing, so I'm unsure if there is some "dependency drift" issue here or a legit issue introduced by the PR.

**Comment by lukemelia** [comment]
Test addressed in #174

**Comment by lukemelia** [comment]
Verified that this passes when rebased on master with #174 merged. Merging... Thanks @pieter-v! 🥇

**Comment by lukemelia** [comment]
Released as 1.0.0-alpha.9

**Pull request merged**
