### PR TITLE
Use yarn instead of npm

### PR DESCRIPTION
**Pull request by Turbo87**
/cc @rwjblue

### CODE REVIEW

**Comment by rwjblue** [comment]
Don't you also need to add `useYarn: true` to the try config?

**Comment by Turbo87** [comment]
not sure, seems to work "fine" without?

**Comment by rwjblue** [comment]
Ya, it works as long as it uses npm < 5.  It will troll us locally though (if we use node 8).

**Comment by Turbo87** [comment]
wait, you mean you didn't downgrade npm to 4.x? :trollface:

**Comment by rwjblue** [comment]
loooooll, no 😡

**Comment by Turbo87** [comment]
@rwjblue updated the configs to use the yarn flag

**Pull request merged**
