### PR TITLE
Glimmer 2 Compatibility

### PR DESCRIPTION
**Pull request by paddyobrien**
For https://github.com/emberjs/ember-collection/issues/126

Adding support for glimmer 2. Would appreciate any feedback on the approach.

### CODE REVIEW

**Comment by GavinJoyce** [comment]
FYI It doesn't look like CI is running the beta build (at least I can't see it in the output)

**Comment by GavinJoyce** [comment]
Some [discussion](https://embercommunity.slack.com/archives/dev-glimmer/p1478102140001783):

screen shot 2016-11-02 at 20 36 01
screen shot 2016-11-02 at 20 36 11

**Comment by GavinJoyce** [comment]
We're going to run this branch in production in Intercom as is for a little while.

**Comment by stefanpenner** [comment]
having some issues getting this working locally...

**Comment by stefanpenner** [comment]
if the blocker is glimmer support or not, maybe we should just bump a major version?

**Comment by stefanpenner** [comment]
> having some issues getting this working locally.

It appears this doesn't work locally, that is likely something we must see to consider merge.

**Comment by stefanpenner** [comment]
https://github.com/emberjs/ember-collection/pull/131 gets the dummy app started

**Comment by stefanpenner** [comment]
> #131 gets the dummy app started

@lukemelia / @krisselden either of you guys some cycles to review. Dummy app seems to be functional

**Comment by lukemelia** [comment]
@stefanpenner looks good to me. We'll need to get ember-try running tests for it.

**Comment by stefanpenner** [comment]
@lukemelia #131  does this I believe.

**Comment by stefanpenner** [comment]
merging this and then #131

**Pull request merged**
